/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import org.junit.Test;
import java.io.FileNotFoundException;
import static org.junit.Assert.*;
import static quotes.App.randomQuoteFromJSon;
import static quotes.App.readQuotes;

public class AppTest {

    @Test public void testNotEmptyRandomQuoteFromJSon() throws FileNotFoundException
    {
        String local_Backup = "src/main/resources/recentquotes.json";
        Quotes[] quotes = readQuotes(local_Backup);
        randomQuoteFromJSon(quotes);
        assertNotEquals("Should Contain a Quote", "", randomQuoteFromJSon(quotes));
    }

    @Test public void testNotEmptyRandomQuoteFromStarryQuotes() throws FileNotFoundException
    {
        String local_Backup = "src/main/resources/recentquotes.json";
        Quotes[] quotes = readQuotes(local_Backup);
        randomQuoteFromJSon(quotes);
        assertNotEquals("Should Contain a Quote", "", randomQuoteFromJSon(quotes));
    }

}
