/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import org.junit.Test;
import java.io.FileNotFoundException;
import java.net.MalformedURLException;

import static org.junit.Assert.*;
import static quotes.App.*;

public class AppTest {

    @Test public void testNotEmptyRandomQuoteFromJSon() throws FileNotFoundException
    {
        String local_Backup = "src/main/resources/recentquotes.json";
        Quotes[] quotes = readLocalQuotes(local_Backup);
        assertNotEquals("Should Contain a Quote", "", randomQuoteFromJSon(quotes));
    }

    @Test public void testNoAPICallErrorRandomQuoteFromStarryQuotes() throws FileNotFoundException, MalformedURLException {
        String apiEndPoint = "http://swquotesapi.digitaljedi.dk/api/SWQuote/RandomStarWarsQuote";
        String backup_Local = "src/main/resources/recentquotes.json";
        assertNotEquals("Should Contain a Quote", "API call error, reading from local backup file", goGetItOnline(apiEndPoint, backup_Local));
    }

}
